### ISSUE TITLE
[0.5] 1a: Revise main navigation items

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#27]
Remove the Search and Browse items from the main navigation. In their place, add an Explore Collections item that links to this page:

https://www.collegewomen.org/browse

![college women open access portal](https://user-images.githubusercontent.com/20477677/34013911-42b1be50-e0e7-11e7-905d-aedf64412b82.png)

**Comment by amberreeves** [comment]
@cworthen this link should just say **Browse Collection** (without the word 'item'). sorry if there was confusion in the wording there!

also, can you check the hover state? i'm seeing the entire link in a gray bubble, but with the other links in that navigation, the text itself just turns gray. @mtedeschi can you confirm this link should behave the same way as the others?

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=sports

![screen shot 2018-02-05 at 3 56 27 pm](https://user-images.githubusercontent.com/20477677/35828371-3b29ee44-0a8d-11e8-9ff1-0433642c3000.png)

**Comment by mtedeschi** [comment]
@amberreeves, @cworthen: agreed on the hover state. If we can just remove the gray background, that should do it.

**Comment by amberreeves** [comment]
the hover state is gone but the text here still needs to be edited. it should say Browse Collection (without the word 'item')

**Comment by mtedeschi** [comment]
Fixed.

**Comment by amberreeves** [comment]
i still see the word 'Item' here -  in the nav item that is supposed to say Explore Collections

https://bmc-d7-college-women.pantheonsite.io/

![college women open access portal](https://user-images.githubusercontent.com/20477677/36444686-064273ea-164a-11e8-9adb-52fbf8366f96.png)

**Comment by cworthen** [comment]
@amberreeves removing right now

**Comment by cworthen** [comment]
@amberreeves fixed

**Comment by amberreeves** [comment]
please add the **s** to the end so that this says 

**Explore Collections**

**Comment by amberreeves** [comment]
looks good
