### ISSUE TITLE
[0.25] 1d: Change text on search results when no items found

### ISSUE THREAD

**Issue by amberreeves** [InteractiveMechanics/CollegeWomen_Drupal7#30]
When someone does a search on the Explore Collections page, and no search results are returned, the site currently says:

No browse items found.
Back to browse page (link to the Explore Collections page)

Please change these to say:
 
No items found.
Back to Explore Collections (link to the Explore Collections page)

Example search results page with no items found:
https://www.collegewomen.org/browse?searchterm=rainbows&start_year=&end_year=&subject=&type=&institution=

![browse open access portal 3](https://user-images.githubusercontent.com/20477677/34014301-aeec424c-e0e8-11e7-9e9a-0ad56796c07f.png)

**Comment by mtedeschi** [comment]
Located in the View:
/admin/structure/views/view/browse/edit

**Comment by mtedeschi** [comment]
@cworthen: this is incomplete. The link text needs to read: "Back to Explore Collections"

**Comment by amberreeves** [comment]
the text that displays when no items found is correct. 
No items found. 
Back to Explore Collections (link to the Search results page, is this correct?)

However, there are some other issues with this page. The csv/txt/json buttons are displaying and linking to blank files and the 'items found' text at the top should say '0 items found'

![browse open access portal](https://user-images.githubusercontent.com/20477677/36383914-903c7a9a-155b-11e8-9777-d8cb9615c2d5.png)

**Comment by mtedeschi** [comment]
Fixed the blank items found issue. Looking into hiding the icons for downloads.

**Comment by amberreeves** [comment]
still seeing this @mtedeschi, can you take a look?

https://bmc-d7-college-women.pantheonsite.io/browse?searchterm=chaos&start_year=&end_year=&type=&institution=All&theme_id=All

**Comment by amberreeves** [comment]
nevermind, wrong branch. however, this is what i'm seeing now on the right branch.

https://dev-college-women.pantheonsite.io/browse?searchterm=ouija

![browse open access portal](https://user-images.githubusercontent.com/20477677/36602334-c65df612-1885-11e8-994b-619046ef651d.png)

**Comment by mtedeschi** [comment]
It looks like we need to make sure that the "Viewing all items" should be the "0 items found" message.

**Comment by cworthen** [comment]
@mike @amberreeves  I was able to get the 0 items found to work, it changes the way 'viewing all' items is display. For example, `<?php	if (strpos($_SERVER['REQUEST_URI'], "start") == false){ ?>`it won't print no items found even though 'start' is not in the url. I had to set the condition to true, to this 'no items found' to show. By doing that, 'Viewing all item' only works if visitors use the advanced search with everything selected.

**Comment by mtedeschi** [comment]
Good to go.

**Comment by amberreeves** [comment]
From Evan
“Viewing all # items” should only be applied when you're viewing all items on the site. 
Currently when I search from the search window and it pulls up a limited selection of results I get the “# items found” language, which is good.
But if I narrow the results further by clicking a theme link in the Theme Column, or Dates, it says “Viewing all # items” which is weird if it says “82” not “1322” and is clearly not all the items in the site. 
Ideally it would say “found” in that case, or after any searching or filtering has been applied. 
“All” should only be used when the user is viewing the entire site contents.

From Amber
I understand what she's saying, but the text is essentially saying you're "Viewing all # items" that match your search filters, right? So I think we just have to decide if we want to do more on this or explain what the intent is here.

**Comment by cworthen** [comment]
@amberreeves @mtedeschi Was there a decision made on how to proceed ? Should the intent be explained or should more be done with the text  ?

**Comment by cworthen** [comment]
I think if the original intent is to say you're viewing all items that match the search filters, then that could be explained to the client.  Plus users can see the theme selected underneath, which will signal that they're 'viewing all' results from the filter/link selected.

**Comment by mtedeschi** [comment]
I think there is an easy solution:
The browse page checks for the "?searchterm=" piece of the querystring to determine whether or not to show the "Viewing all [x] items" phrasing or not. The themes links don't add that, so if we just add "?searchterm=" to the links that should resolve this issue.

**Comment by cworthen** [comment]
oh cool, that what I did to fix #56 Theme filter not refreshing...looks like this solution fixed two problems instead of one, which is always a beautiful thing. Thanks Mike!

**Comment by amberreeves** [comment]
looks good
